apiVersion: batch/v1
kind: CronJob
metadata:
  name: apply-policy
  namespace: kube-system
spec:
  schedule: "0 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apply-policy
            image: google/cloud-sdk:slim # GCP image with kubectl
            command:
            - /bin/sh
            - -c
            - |
              EXCLUDED_NAMESPACES=("gke-managed-system" "gmp-public" "gmp-system" "kube-node-lease" "kube-public" "kube-system")
              echo "Applying policy to all namespaces..."
              for ns in $(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}'); do
                if [[ " ${EXCLUDED_NAMESPACES[@]} " =~ " ${namespace} " ]]; then
                  echo "Skipping excluded namespace: ${namespace}"
                  continue
                fi
                echo "Applying policy to namespace: $ns"
                kubectl label namespace "$ns" pod-security.kubernetes.io/enforce=restricted --overwrite
              done
              echo "Policy applied successfully!"
          restartPolicy: OnFailure
