sonar.projectKey=Stellar-Engine
sonar.qualitygate.wait=true
sonar.sarifReportPaths=reports/blueprints-checkov.sarif,reports/stages-checkov.sarif
sonar.terraform.tflint.reportPaths=reports/blueprints-tflint.sarif,reports/stages-tflint.sarif
