apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoOwnerReference
metadata:
  name: pod-must-have-owner
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludeNamespaces:
      - "kube-system"
      - "kube-public"
      - "gatekeeper-system"